{{ Html::style('http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all') }}
{{ Html::style('assets/global/plugins/font-awesome/css/font-awesome.min.css') }}
{{ Html::style('assets/global/plugins/simple-line-icons/simple-line-icons.min.css') }}
{{ Html::style('assets/global/plugins/bootstrap/css/bootstrap.min.css') }}
{{ Html::style('assets/global/plugins/uniform/css/uniform.default.css') }}
{{ Html::style('assets/global/plugins/select2/select2.css') }}
{{ Html::style('assets/admin/pages/css/login-soft.css') }}
{{ Html::style('assets/global/css/components.css') }}
{{ Html::style('assets/global/css/plugins.css') }}
{{ Html::style('assets/admin/layout/css/layout.css') }}
{{ Html::style('assets/admin/layout/css/themes/darkblue.css') }}
{{ Html::style('assets/admin/layout/css/custom.css') }}
